In [13]:
import pandas as pd

print("\n==============================")
print("ETAPA 1 - EXTRAÇÃO")
print("==============================")

# Interoperabilidade Técnica:
# Estamos lendo arquivos CSV de sistemas diferentes.

vendas = pd.read_csv("vendas.csv")
produtos = pd.read_csv("produtos.csv")

display(vendas)

display(produtos)

==============================
ETAPA 1 - EXTRAÇÃO
==============================

     sku  qtd
0   P044   15
1   P010   20
2   P074    9
3   P076   12
4   P001   10
..   ...  ...
95  P004    3
96  P045   12
97  P034   14
98  P072    1
99  P003    9

[100 rows x 2 columns]

     sku         nome  preco
0   P001       Webcam    795
1   P002     Mousepad    549
2   P003        Mouse   2226
3   P004      Teclado   2414
4   P005     Mousepad   2267
..   ...          ...    ...
95  P096           HD   1220
96  P097       Webcam    524
97  P098      Headset    205
98  P099        Mouse   1498
99  P100  Memória RAM   2053

[100 rows x 3 columns]

In [14]:
import pandas as pd

# print("\n==============================")
# print("ETAPA 1 - EXTRAÇÃO")
# print("==============================")

# Interoperabilidade Técnica:
# Estamos lendo arquivos CSV de sistemas diferentes.

vendas = pd.read_csv("vendas.csv")
produtos = pd.read_csv("produtos.csv")

print("\n==============================")
print("ETAPA 2 - TRANSFORMAÇÃO")
print("==============================")

# ============================================================
# INTEROPERABILIDADE SEMÂNTICA
# O SKU é o elo de ligação entre sistemas que "falam línguas diferentes".
# Ele garante que estamos unindo o produto correto à venda correta.
# ============================================================

dw = pd.merge(vendas, produtos, on="sku")

display(dw.head())


# ============================================================
# REGRA DE NEGÓCIO - MÉTRICA DE FATURAMENTO
# ============================================================

dw["faturamento"] = dw["qtd"] * dw["preco"]

display(dw.head())


# ============================================================
# GOVERNANÇA - PADRONIZAÇÃO
# ============================================================

dw["nome"] = dw["nome"].str.upper()

display(dw.head())

==============================
ETAPA 2 - TRANSFORMAÇÃO
==============================

    sku  qtd     nome  preco
0  P044   15    Mouse    634
1  P010   20   Webcam    906
2  P074    9  Monitor   1972
3  P076   12  Headset   2870
4  P001   10   Webcam    795

    sku  qtd     nome  preco  faturamento
0  P044   15    Mouse    634         9510
1  P010   20   Webcam    906        18120
2  P074    9  Monitor   1972        17748
3  P076   12  Headset   2870        34440
4  P001   10   Webcam    795         7950

    sku  qtd     nome  preco  faturamento
0  P044   15    MOUSE    634         9510
1  P010   20   WEBCAM    906        18120
2  P074    9  MONITOR   1972        17748
3  P076   12  HEADSET   2870        34440
4  P001   10   WEBCAM    795         7950

In [15]:
import pandas as pd

# print("\n==============================")
# print("ETAPA 1 - EXTRAÇÃO")
# print("==============================")

# Interoperabilidade Técnica:
# Estamos lendo arquivos CSV de sistemas diferentes.

vendas = pd.read_csv("vendas.csv")
produtos = pd.read_csv("produtos.csv")

print("\n==============================")
print("ETAPA 2 - TRANSFORMAÇÃO")
print("==============================")

# ============================================================
# INTEROPERABILIDADE SEMÂNTICA
# O SKU é o elo de ligação entre sistemas que "falam línguas diferentes".
# Ele garante que estamos unindo o produto correto à venda correta.
# ============================================================

dw = pd.merge(vendas, produtos, on="sku")

display(dw.head())


# ============================================================
# REGRA DE NEGÓCIO - MÉTRICA DE FATURAMENTO
# ============================================================

dw["faturamento"] = dw["qtd"] * dw["preco"]


display(dw.head())


# ============================================================
# GOVERNANÇA - PADRONIZAÇÃO
# ============================================================

dw["nome"] = dw["nome"].str.upper()

display(dw.head())

==============================
ETAPA 2 - TRANSFORMAÇÃO
==============================

    sku  qtd     nome  preco
0  P044   15    Mouse    634
1  P010   20   Webcam    906
2  P074    9  Monitor   1972
3  P076   12  Headset   2870
4  P001   10   Webcam    795

    sku  qtd     nome  preco  faturamento
0  P044   15    Mouse    634         9510
1  P010   20   Webcam    906        18120
2  P074    9  Monitor   1972        17748
3  P076   12  Headset   2870        34440
4  P001   10   Webcam    795         7950

    sku  qtd     nome  preco  faturamento
0  P044   15    MOUSE    634         9510
1  P010   20   WEBCAM    906        18120
2  P074    9  MONITOR   1972        17748
3  P076   12  HEADSET   2870        34440
4  P001   10   WEBCAM    795         7950