In [26]:
import pandas as pd

print("\n==============================")
print("ETAPA 1 - EXTRAÇÃO")
print("==============================")

==============================
ETAPA 1 - EXTRAÇÃO
==============================


# Interoperabilidade Técnica:
# Estamos lendo arquivos CSV de sistemas diferentes.

In [27]:


vendas = pd.read_csv("vendas.csv")
produtos = pd.read_csv("produtos.csv")

In [28]:
display("\n==============================")
display("ETAPA 2 - TRANSFORMAÇÃO")
display("==============================")

'\n=============================='

'ETAPA 2 - TRANSFORMAÇÃO'

'=============================='

# ============================================================
# INTEROPERABILIDADE SEMÂNTICA
# O SKU é o elo de ligação entre sistemas que "falam línguas diferentes".
# Ele garante que estamos unindo o produto correto à venda correta.
# ============================================================

In [29]:
dw = pd.merge(vendas, produtos, on="sku")

display("\nTabela após Merge (Integração):")
display(dw.head())

'\nTabela após Merge (Integração):'

    sku  qtd     nome  preco
0  P044   15    Mouse    634
1  P010   20   Webcam    906
2  P074    9  Monitor   1972
3  P076   12  Headset   2870
4  P001   10   Webcam    795

# ============================================================
# REGRA DE NEGÓCIO - MÉTRICA DE FATURAMENTO
# ============================================================

In [30]:

dw["faturamento"] = dw["qtd"] * dw["preco"]

display("\nTabela com Faturamento Calculado:")
display(dw.head())

'\nTabela com Faturamento Calculado:'

    sku  qtd     nome  preco  faturamento
0  P044   15    Mouse    634         9510
1  P010   20   Webcam    906        18120
2  P074    9  Monitor   1972        17748
3  P076   12  Headset   2870        34440
4  P001   10   Webcam    795         7950

# ============================================================
# GOVERNANÇA - PADRONIZAÇÃO
# ============================================================

In [31]:
dw["nome"] = dw["nome"].str.upper()

display("\nTabela após Padronização (Nomes em MAIÚSCULO):")
display(dw.head())

'\nTabela após Padronização (Nomes em MAIÚSCULO):'

    sku  qtd     nome  preco  faturamento
0  P044   15    MOUSE    634         9510
1  P010   20   WEBCAM    906        18120
2  P074    9  MONITOR   1972        17748
3  P076   12  HEADSET   2870        34440
4  P001   10   WEBCAM    795         7950

In [32]:

display("\n==============================")
display("ETAPA 3 - CARGA")
display("==============================")

# Persistência do Data Warehouse
dw.to_csv("data_warehouse_final.csv", index=False)

display("Arquivo data_warehouse_final.csv criado com sucesso!")

'\n=============================='

'ETAPA 3 - CARGA'

'=============================='

'Arquivo data_warehouse_final.csv criado com sucesso!'